version: "3"

services:
  sdp.statoil.no:
    image: nginx:latest
    container_name: "sdp.statoil.no"
    hostname: "sdp.statoil.no"
    restart: "unless-stopped"
    volumes:
      - ./src:/usr/share/nginx/html:ro
    ports:
      - "9001:80"
